//! component-echo: the minimal `plugin` world sample.
//!
//! `init` registers one element; `evaluate` (generated by
//! [`notist_plugin_sdk::export_plugin!`]) echoes the bound arguments and the
//! trailing body back as a self-named Leaf.

use notist_plugin_sdk::{Args, ElementDecl, ElementFn, EvalCtx, Node, Registrar, Value};

pub struct Echo;

impl ElementFn for Echo {
    fn decl(&self) -> ElementDecl {
        ElementDecl::new("echo")
            .block(true)
            .param_default("message", "String", "\"hello\"")
            .trailing_content("body")
            .body_mode("flow")
    }

    fn reduce(
        &self,
        ctx: &mut EvalCtx<'_>,
        args: &Args,
        body: &[Node],
    ) -> Result<Vec<Node>, String> {
        let message = args.get_string("message").unwrap_or("hello");
        // Name the leaf after the dispatched call so repackaging the same
        // binary under another package id keeps the leaf names aligned with
        // the host registration namespace.
        let mut leaf = Node::leaf(ctx.call_name(), true);
        for node in body {
            leaf = leaf.child(node.clone());
        }
        Ok(vec![leaf.field("message", Value::from(message))])
    }
}

pub struct Plugin;

impl notist_plugin_sdk::Plugin for Plugin {
    fn init(registrar: &mut Registrar) {
        registrar.element(Echo);
    }
}

notist_plugin_sdk::export_plugin!("component-echo", Plugin);
