[package]
name = "notist-plugin-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
toml.workspace = true
zip = "2.4.2"
wasmi = "1.1"
notist-eval.workspace = true
notist-model.workspace = true

[dev-dependencies]
notist-plugin-core.workspace = true
