[package]
name = "notist-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "notist"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
notist-analysis = { path = "../notist-analysis" }
notist-html = { path = "../notist-html" }
serde_json.workspace = true
lsp-server = "0.10"
tiny_http = "0.12"
url = "2"

[dev-dependencies]
tempfile = "3"
