[package]
name = "notist-plugin-mermaid-wasm"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mermaid-rs-renderer = { version = "0.3.1", default-features = false }
notist-model = { path = "../../../crates/notist-model" }
notist-plugin-sdk = { path = "../../../crates/notist-plugin-sdk" }
