[package]
name = "notist-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
dunce.workspace = true
notify-debouncer-mini.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
regex.workspace = true
tantivy.workspace = true
tokio.workspace = true
unicode-normalization.workspace = true
notist-analysis.workspace = true
notist-model.workspace = true
notist-syntax.workspace = true
notist-html.workspace = true
percent-encoding.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Pipes",
    "Win32_System_Threading",
] }

[dev-dependencies]
tempfile.workspace = true
