[package]
name = "notist-next"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["filesystem"]
filesystem = ["notist-analysis/filesystem"]

[dependencies]
notist-syntax = { path = "../notist-syntax" }
notist-ir = { path = "../notist-ir" }
notist-eval = { path = "../notist-eval" }
notist-analysis = { path = "../notist-analysis", default-features = false }
serde_json.workspace = true
base64 = "0.22"
web-time = "1"

[dev-dependencies]
notist-model = { path = "../notist-model" }
notist-html = { path = "../notist-html" }
wat = "1"
