[package]
name = "notist-ssg"
version = "0.1.0"
edition = "2024"

[dependencies]
notist = { path = "../.." }
notist-html = { path = "../notist-html" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
globset = "0.4"
handlebars = { version = "6", default-features = false }
percent-encoding = "2"

[dev-dependencies]
tempfile = "3"
